os:
   - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install packer; fi
  - brew install Caskroom/cask/virtualbox
  - brew install Caskroom/cask/vagrant
script:
  - make all
